[project]
name = "berichtsheft-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nicegui>=2.23.0",
    "pypdf2>=3.0.1",
    "reportlab>=4.4.3",
]
